

# Syntax https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      # hard rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone   # here lable which zone lo vudho aa node lo pod will go into scheduler...
            operator: In
            values:
            - us-east-1b

            # this EX so here disktype ssd vunnna node ki, pod will assignee ......
          # - key: disktype
          #   operator: In
          #   values:
          #   - ssd

      # soft rule
      preferredDuringSchedulingIgnoredDuringExecution:
      # so here weight ekkuva vunde dhaniki ekkuva preference
      - weight: 100
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshop
      - weight: 10
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - amazon
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
